### ISSUE TITLE
gWidgets

### ISSUE THREAD

**Issue by bluetyson** [gtkfi/MapWizard#1]
FYI

https://cran.r-project.org/web/packages/gWidgets/index.html

Package ‘gWidgets’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2020-06-05.

Please use the canonical form https://CRAN.R-project.org/package=gWidgets to link to this page.

**Comment by sahautal** [comment]
Thanks for the information. The package ´gWidgets´ will anyways be removed from future versions of MapWizard.

**Comment by sahautal** [comment]
The package  ‘gWidgets’ is no longer used in MapWizard.
